import databaseTools
import mook
import tkinter as tk
from tkinter import ttk 
from PIL import ImageTk, Image
import numbers

db = databaseTools.databaseTools()

win = tk.Tk()
win.geometry("753x508")
win.title("Cyberpunk Red Mook Adder")

background_image = Image.open("background.jpg")
background = ImageTk.PhotoImage(background_image)
image_label = tk.Label(win , image = background)
image_label.place(x = 0 , y = 0)

mooknaname_text = tk.Text(win, height=1, width=20, font=("Arial", 12), bg='#fff', fg='#000')
mooknaname_text.place(x=80, y=25)
mookrole_text = tk.Text(win, height=1, width=20, font=("Arial", 12), bg='#fff', fg='#000')
mookrole_text.place(x=80, y=66)
mookrep_text = tk.Text(win, height=1, width=3, font=("Arial", 12), bg='#fff', fg='#000')
mookrep_text.place(x=435, y=25)
mookseriouslywounded_label = tk.Label(win, text="0", font=("Arial", 12), bg='#fff', fg='#000')
mookseriouslywounded_label.place(x=580, y=25)
mookdeathsave_label = tk.Label(win, text="0", font=("Arial", 12), bg='#fff', fg='#000')
mookdeathsave_label.place(x=580, y=66)
mookhp_label = tk.Label(win, text="0", font=("Arial", 20), bg='#fff', fg='#000')
mookhp_label.place(x=692, y=39)
intlabel = tk.Label(win, text="INT ", font=("Arial", 12), bg='#bbb', fg='#000')
intlabel.place(x=10, y=128)
mookint_label = tk.Label(win, text="int", font=("Arial", 12), bg='#fff', fg='#000')
mookint_label.place(x=45, y=128)
reflabel = tk.Label(win, text="REF ", font=("Arial", 12), bg='#bbb', fg='#000')
reflabel.place(x=63, y=128)
mookref_label = tk.Label(win, text="ref", font=("Arial", 12), bg='#fff', fg='#000')
mookref_label.place(x=115, y=128)
dexlabel = tk.Label(win, text="DEX ", font=("Arial", 12), bg='#bbb', fg='#000')
dexlabel.place(x=140, y=128)
mookdex_label = tk.Label(win, text="dex", font=("Arial", 12), bg='#fff', fg='#000')
mookdex_label.place(x=200, y=128)
techlabel = tk.Label(win, text="TECH", font=("Arial", 12), bg='#bbb', fg='#000')
techlabel.place(x=225, y=128)
mooktech_label = tk.Label(win, text="tech", font=("Arial", 12), bg='#fff', fg='#000')
mooktech_label.place(x=280, y=128)
coollabel = tk.Label(win, text="COOL", font=("Arial", 12), bg='#bbb', fg='#000')
coollabel.place(x=300, y=128)
mookcool_label = tk.Label(win, text="cool", font=("Arial", 12), bg='#fff', fg='#000')
mookcool_label.place(x=355, y=128)
willlabel = tk.Label(win, text="WILL", font=("Arial", 12), bg='#bbb', fg='#000')
willlabel.place(x=375, y=128)
mookwill_label = tk.Label(win, text="will", font=("Arial", 12), bg='#fff', fg='#000')
mookwill_label.place(x=423, y=128)
lucklabel = tk.Label(win, text="LUCK", font=("Arial", 12), bg='#bbb', fg='#000')
lucklabel.place(x=445, y=128)
mookluck_label = tk.Label(win, text="0", font=("Arial", 12), bg='#fff', fg='#000')
mookluck_label.place(x=497, y=128)
movelabel = tk.Label(win, text="MOVE", font=("Arial", 12), bg='#bbb', fg='#000')
movelabel.place(x=515, y=128)
mookmove_label = tk.Label(win, text="move", font=("Arial", 12), bg='#fff', fg='#000')
mookmove_label.place(x=580, y=128)
bodylabel = tk.Label(win, text="BODY", font=("Arial", 12), bg='#bbb', fg='#000')
bodylabel.place(x=610, y=128)
mookbody_label = tk.Label(win, text="body", font=("Arial", 12), bg='#fff', fg='#000')
mookbody_label.place(x=663, y=128)
emplabel = tk.Label(win, text="EMP", font=("Arial", 12), bg='#bbb', fg='#000')
emplabel.place(x=680, y=128)
mookemp_label = tk.Label(win, text="emp", font=("Arial", 12), bg='#fff', fg='#000')
mookemp_label.place(x=725, y=128)
mookweapon1name_label = tk.Label(win, text="w1", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon1name_label.place(x=20, y=186)
mookweapon1rof_label = tk.Label(win, text="rof", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon1rof_label.place(x=361, y=186)
mookweapon1damage_label = tk.Label(win, text="dmg", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon1damage_label.place(x=441, y=186)
mookweapon2name_label = tk.Label(win, text="w2", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon2name_label.place(x=20, y=219)
mookweapon2rof_label = tk.Label(win, text="rof", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon2rof_label.place(x=361, y=219)
mookweapon2damage_label = tk.Label(win, text="dmg", font=("Arial", 12), bg='#fff', fg='#000')
mookweapon2damage_label.place(x=441, y=219)
mookarmourhead_label = tk.Label(win, text="head", font=("Arial", 12), bg='#fff', fg='#000')
mookarmourhead_label.place(x=522, y=186)
mookarmourheadsp_label = tk.Label(win, text="spec", font=("Arial", 12), bg='#fff', fg='#000')
mookarmourheadsp_label.place(x=698, y=186)
mookarmourbody_label = tk.Label(win, text="body", font=("Arial", 12), bg='#fff', fg='#000')
mookarmourbody_label.place(x=522, y=219)
mookarmourbodysp_label = tk.Label(win, text="spec", font=("Arial", 12), bg='#fff', fg='#000')
mookarmourbodysp_label.place(x=698, y=219)
mookskills_label = tk.Label(win, text="skills", font=("Arial", 9), wraplength=733, justify="left", bg='#fff', fg='#000')
mookskills_label.place(x=10, y=270)
mookequipment_label = tk.Label(win, text="equipment", font=("Arial", 9), wraplength=733, justify="left", bg='#fff', fg='#000')
mookequipment_label.place(x=10, y=368)
mookcyberwear_label = tk.Label(win, text="cyberwear", font=("Arial", 9), wraplength=733, justify="left", bg='#fff', fg='#000')
mookcyberwear_label.place(x=10, y=450)



win.mainloop()